# -*- coding: utf-8 -*-
"""AppleQuality.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/170WMzHUuqGtWF2mXMi4o0QVd1mVUyk0n
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data=pd.read_csv("/content/apple_quality.csv")

data.head()

data.isnull().sum()

data.dropna(inplace=True)

data.isnull().sum()

data = data.drop("A_id", axis=1)
data.head()

data["Quality"] = data["Quality"].replace("good", 1)

# "bad" değerlerini 0 ile değiştir
data["Quality"] = data["Quality"].replace("bad", 0)

data.head()

x=data.drop("Quality",axis=1)
y=data["Quality"]

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.4,random_state=52)

from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier( max_depth=16, random_state=16)

rf.fit(x_train,y_train)

y_pred=rf.predict(x_test)

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
skor=accuracy_score(y_test, y_pred)

print(skor)